// this file was generated by better-cmake
// mg v0.8.0

#define mg_NAME "mg"
#define mg_AUTHOR "DaemonTsun"
#define mg_VERSION "0.8.0"
#define mg_VERSION_MAJOR 0
#define mg_VERSION_MINOR 8
#define mg_VERSION_PATCH 0
